### ISSUE TITLE
iOS: XCode errors when uploading to the App Store

### ISSUE THREAD

**Issue by LeonardoDemartino** [Purchasely/Unity-Package#12]
When uploading to the App Store/TestFlight I've got these errors:
<img width="674" alt="purchasely_upload_error" src="https://github.com/Purchasely/Unity-Package/assets/14348106/c2a51653-55e0-4bce-8895-2c7876bbf506">

After removing Purchasely.xcframework from "Copy Bundles Resources" phase it worked.

**Comment by kherembourg** [comment]
@LeonardoDemartino Can you tell us if with the last version 4.1.4 you have to remove Purchasely.xcframework again?
Thanks in advance!
