### ISSUE TITLE
iOS: ShowPresentation crashes app

### ISSUE THREAD

**Issue by LeonardoDemartino** [Purchasely/Unity-Package#31]
I'm using Purchasely.HidePresentation() to show our own parental gate on Unity (this happens as soon as the user presses the purchase button).
After intercepting it and showing the parental gate, I need to show the presentation again, but when I call Purchasely.ShowPresentation() the app crashes with:
`Uncaught exception: NSInvalidArgumentException: Pushing a navigation controller is not supported`
...

Question: Is it possible to show a Unity canvas in front of the Purchasely canvas? I've tried with no luck, it seems that since Purchasely is rendering natively, Unity is rendered always on the background. I'm asking just in case you have found a way to do this and to avoid calling Hide/Show Presentation.

**Comment by EPIKorial** [comment]
Hello @LeonardoDemartino, Thank you for reaching out to us for this issue.

After investigating, you are right we have a bug with the ShowPresentation method, i fixed it and it will be available in the next release of the Unity Bridge that should arrive very soon.

About your question, i think it might be possible by using the **_Render over native UI_** option in the **_Player Settings_** > **_Resolution and Presentation_** menu.
I haven't tried it myself but this is the purpose of this option. 

I will notify you as soon as we release the new version, don't hesitate to come back at us if you encounter any other issue.

Best regards,

Florian
